### ISSUE TITLE
Create new location param type

### ISSUE THREAD

**Issue by kddnewton** [Shopify/yarp#200]
When we template out our AST and related code, we have a couple of different kinds of parameters that can be added onto nodes. Those include:

* `node` - another node
* `node?` - an optional node
* `node[]` - a list of nodes
* `token` - a token
* `token?` - an optional token
* `token[]` - a list of tokens
* `string` - a string of characters

For the most part, this information is enough. However, there are times when it is redundant. For example, the `DefinedNode` node has a `token` for its keyword on it that is always going to be `defined?`. 

Instead, we should create a `location` parameter that only stores the location in source. That way we'll save a bit on the overall memory that both the AST and serialization require. The `location` parameter should be its own struct that just stores two offsets into the source. Once we have that parameter in place, we should replace parameters in the existing tree that are constant to take advantage of this work. Finally, we should reorder the nodes so that the location parameters are always at the end, so that consumers of the serialization don't have to worry about them and can skip past them.

- [ ] Create a new `location` parameter type
- [ ] Replace tokens that are constant in the tree with the new parameter type
- [ ] Move those tokens to the end of the list of child nodes

**Comment by eregon** [comment]
I wonder a bit if we need a location type and whether it's useful to move those at the end of child nodes. I'm thinking we might not need to serialize tokens at all for Ruby interpreters/for the semantics AST.

* I guess in any case for Ruby interpreters we probably want the start and end offset for every node (or almost every node to the point of better be every for consistency). That's already there and stored efficiently:
https://github.com/Shopify/yarp/blob/b9dd811e76d81c77760f2d50f224abf543a640f5/bin/templates/java/org/yarp/Nodes.java.erb#L16-L17

* For Tokens in general I think we don't need those for Ruby interpreters. So my thought was we have a mode where tokens simply don't get serialized at all. We just have a the start/end offset for each node, and then the existing fields/child nodes to find the rest of the information. As an example for an integer literal node, we'd use either the start/end offset which anyway is the same as the token, or there would be a string field or an integer field. For a call node we probably don't need much besides flags (e.g. for &., fcall, etc), method name and children nodes. We might an extra offset or a way to know where the `.` is for error_highlight purposes. Do you think that approach makes sense or you think we should use something else?

**Comment by eregon** [comment]
To clarify, no objection to have a location type, which e.g. could be the same as `yp_location_t` and notably every node has a location (https://github.com/Shopify/yarp/pull/84#discussion_r1009680907).
More about whether we need to serialize tokens at all or not.

**Comment by eregon** [comment]
> As an example for an integer literal node, we'd use either the start/end offset which anyway is the same as the token, or there would be a string field or an integer field.

Although that wouldn't work for a complex literal node (e.g., `123i`), where we'd want the location without the `i`, or a field with `123` (as string or integer).

**Comment by eregon** [comment]
Maybe let's chat tomorrow/this week to sync on this?

**Comment by kddnewton** [comment]
> Maybe let's chat tomorrow/this week to sync on this?

Yeah for sure. I think it would make sense even to drop some tokens for CRuby as well.

**Comment by enebo** [comment]
It seems for Ruby 3.2 we are required for all/most nodes to be aware of start/end so we can underline things.   So I think all Node will have two those fields and should not require another type as it just adds memory.  An object instance in Java has overhead whereas that overhead is already paid in Node if we just use them as fields.

I think this previous paragraph applies that we do not want some specifier of location type in the stream but just want nodes to have start/end offsets.

It makes sense to me as @eregon says to elide data when the offset can reference it.  It means reading from two arrays but we already are leveraging the source so that seems like a reasonable continuation of that. 

The example @eregon gave is thought-provoking.  If there was a notion of an enum then Integer = IntegerLiteral|ImaginaryLiteral... (maybe even ImaginaryLiteral(is-a: Integer). You want the node to be one of these things and to know it is an integer but from a AST building exercise you really care about whether it is imaginary or something else.  Implementations already know imaginary numbers are integers so serialization does not need to convey this as information. syntax type analysis tools might but I am not sure how broad the scope of yarp is.

**Comment by enebo** [comment]
Ignore my Integer enum thing. If we care about things like base on Integer literals we can just make more Node types or IntegerLiteral and IntegerBaseLiteral where we just know one needs to look at the last digit for base used.

**Comment by kddnewton** [comment]
@eregon there are still a few places where you're going to need the token. For example, in `CallNode` the operator that is used to make the call is a token, and you'll need to delineate between `.` and `&.`. That said, we could make that into a `SafeCallNode` if we wanted.

**Comment by kddnewton** [comment]
`3i` is `ImaginaryNode`, `3r` is `RationalNode`, `3ri` is `ImaginaryNode`.

**Comment by kddnewton** [comment]
I'm going to close this issue, as I've added the location param to a couple of places already and it appears to be working/simplifying which is nice.
